### PR TITLE
add jinja language

### PR DESCRIPTION
**Pull request by Destaq**
Add support for the `Jinja` language, a web template engine for Python, more info [here](https://en.wikipedia.org/wiki/Jinja_(template_engine)#:~:text=Jinja%20is%20a%20web%20template,are%20evaluated%20in%20a%20sandbox.).

The Jinja logo is available in their permissively-licensed repository [here](https://github.com/pallets/jinja/blob/master/docs/_static/jinja-logo-sidebar.png).

### CODE REVIEW

**Comment by ahtee** [comment]
the project is licensed under a BSD clause 3:

```
BSD 3-Clause "New" or "Revised" License
A permissive license similar to the BSD 2-Clause License, but with a 3rd clause that prohibits others from using the name of the project or its contributors to promote derived products without written consent.
```

could you open an issue or ask a question asking if you could use the logo and name of the project here?

**Comment by davidism** [comment]
I'm a maintainer of Jinja, sent from pallets/jinja#1289. We don't believe this is related to the BSD license, but as none of us are lawyers, here is a statement:

discord-vscode may use the Jinja logo and name for the purpose of displaying a status message.

**Comment by ahtee** [comment]
Thanks @davidism for your time! Just wanted to check if that was an issue with this PR currently.

**Comment by Destaq** [comment]
@ahtee When do you think we will be able to see Jinja files in `discord-vscode`? Thank you.

**Comment by ahtee** [comment]
@Destaq sorry to keep you waiting but I am not a maintainer of this project, I am just reviewing the changes.

**Comment by iCrawl** [comment]
Merged this locally, thanks.

**Pull request closed without merging**
