### PR TITLE
Create reconnect button/command

### PR DESCRIPTION
**Pull request by DusterTheFirst**
Created a reconnect button and command for easy resuming of Discord RPC without refreshing the window

### CODE REVIEW

**Comment by iCrawl** [comment]
You forgot to rebase?

**Comment by DusterTheFirst** [comment]
i thought i did

**Comment by DusterTheFirst** [comment]
It looks like the only conflict is one line

**Comment by iCrawl** [comment]
Nah, you brought in all the commits regardless. Just rebase and force push your branch.

**Comment by DusterTheFirst** [comment]
wait what?

**Comment by iCrawl** [comment]
image

**Comment by DusterTheFirst** [comment]
```
git rebase
git push --force
```
did nothing

**Comment by iCrawl** [comment]
Ugh. You prolly have to hard reset the branch to master, then reapply your changes then.

**Comment by DusterTheFirst** [comment]
but my branch is master

*sorry if i am being an idiot*

**Comment by iCrawl** [comment]
Yea, you didn't fetch from origin before you did your changes. So what happened is you merged your outdated master with mine (the original) and then applied your changes on top of it, which resulted in all the commits you didn't have but I already had in master.

**Comment by DusterTheFirst** [comment]
So how do I get rid of them?

like what do I type in

**Comment by iCrawl** [comment]
Look up how to hard reset a branch with origin and then reapply your changes.

**Comment by DusterTheFirst** [comment]
It does not fetch your branch though, it just outputs
```
HEAD is now at 5127d29 Reconnect button/command
```

**Comment by iCrawl** [comment]
You have to 
```
git fetch origin
git reset --hard origin/master
```

**Comment by DusterTheFirst** [comment]
that is exactly what i did

**Comment by iCrawl** [comment]
And this is why you do branches when you add new features :^)

I guess the only thing left is to refork then. I'm not really at home to check further.

**Comment by DusterTheFirst** [comment]
Okay, ill make sure not to break everything again

**Comment by iCrawl** [comment]
I'll close this for safety reasons.

**Pull request closed without merging**
