### PR TITLE
Fixed language and Dropped updates

### PR DESCRIPTION
**Pull request by DusterTheFirst**
# What I have done
 - **Removed event handlers**
    - not firing under certain circumstances
    - not always accurate file
    - *(Replaced with `setActivity(workspaceElapsedTime);` in the `activityTimer`)*
- **Removed reference to `languages.json` *(did not delete`languages.json`)***
    - did not include many file extensions such as `.ino`
    - *(Changed to `window.activeTextEditor.document.languageId`, as suggested in issue #22 )*

**NOTES:** *Did not do extensive testing, you may need to still use the `languages.json` file for certain languages; In general, the `window.activeTextEditor.document.languageId` system should contain support for many more languages, and can be expanded through extensions*

### CODE REVIEW

**Comment by DusterTheFirst** [comment]
second commit was to remove debugging stuff I forgot

**Comment by iCrawl** [comment]
I don't see how removing the event handlers fixes anything here.
THe event handlers update the variable `activity` correctly. What you may experience as "not firing under certain circumstances" and "not always accurate" is very likely the 15sec timer, if it sends an update the moment you switch files it will obviously be inaccurate for another 15sec. This will also happen with what you changed now.
Removing the language.js is certainly a very bad thing to do considering you need to supply images to EVERY file extension in the discordapp settings. I can not simply add 5 times the same icon for a C file. I will most likely run out of space since there's a limited amount of how many I can have.

**Comment by DusterTheFirst** [comment]
**For your first statement:** The file was not changing for many minutes, and would only change when I were to close out of it and reopen it

**For your second statement:** It is not per file extension, as it is per language. `.h` `.cpp` and `.ino` all give `c++` as the language, it does the language sorting for you. I did overlook that you have all of the images already put into the app; To fix the extension from "requesting" an nonexistent image, you could create a list of all the languages you **do** currently have an icon for, and if there is none available, you could just send a `?` or the image for `plaintext`

**Comment by iCrawl** [comment]
That's a good point. But I currently do not have the time to do that, neither going over the languages.json and make new detection strings/regex, nor the renaming in the keys in the application itself.

So while this may fix bugs (this should really be fully tested before I merge this), I would very much appreciate it to finish this PR. I can simply not deal with having a half finished PR that adds some extra work for myself.

**Comment by DusterTheFirst** [comment]
will do

**Comment by DusterTheFirst** [comment]
I think I did it right

**Pull request merged**
