### PR TITLE
Custom client support

### PR DESCRIPTION
**Pull request by RubenVerg**
I've seen a few requests (me being one of those, really) for settings to change images and/or the title that appears in the rich presence tab. As the way Discord's Rich Presence is structured forbids changing either of those while keeping the same client, this PR adds support for changing the client, as well as a guide on how to create one. Note that the guide (and art assets provided) only documents `vscode-big`, `vscode`, `vscode-insiders`, `debug` and the various file type assets, as these are the ones I found in the code. If there are any others, just let me know.

I also added the `assets/art` folder, that contains replacement icons for all the (known) art assets. Please upload the official ones as soon as possible, as those were neither tested nor checked for contrast or looks on Discord's colors.

### CODE REVIEW

**Comment by iCrawl** [comment]
This features purpesfully removed and most likely won't be reintroduced again.

90% of all people changed the client Id to their own discord user id because they thought this would be the way to go. You are better off just forking this and creating your own local `vscx` package or publishing your own.

**Comment by RubenVerg** [comment]
How does one go change the ID if they don't know what that does? And most importantly, don't you at least look for a guide?

**Comment by RubenVerg** [comment]
Also sidenote, is there any icon I'm missing if I want to package?

**Comment by iCrawl** [comment]
> How does one go change the ID if they don't know what that does? And most importantly, don't you at least look for a guide? 🤔

Yeah, how does one?
I asked that question myself several hundred times. There was even a warning `Don't change this if you don't know what you are doing. You most likely don't.`

And considering 99% of people do not need this feature, I was better off just removing it and telling people who really want to use their own to just build the `vscx` package themselves.

**Pull request closed without merging**
