### PR TITLE
Add PureScript to known languages

### PR DESCRIPTION
**Pull request by spicydonuts**
I'm not sure how the icon works. Is there another step I need to perform elsewhere?

### CODE REVIEW

**Comment by iCrawl** [comment]
You just post the icon here in a comment so I can add it.

**Comment by spicydonuts** [comment]
Does this work? https://github.com/purescript/logo/blob/master/youtube/channel_icon-800.png

**Comment by spicydonuts** [comment]
There are also white and black svgs:
https://github.com/purescript/logo/blob/master/favicon/purescript-favicon-white.svg
https://github.com/purescript/logo/blob/master/favicon/purescript-favicon-white.svg

**Comment by spicydonuts** [comment]
Thanks!

**Pull request merged**
