### PR TITLE
Load Configuration Correctly

### PR DESCRIPTION
**Pull request by PlayTheFallen**
>**Before**  
  

>**After**  
  
  
*+11 other settings*

*To see changes take effect, restart the editor.*

### CODE REVIEW

**Comment by iCrawl** [comment]
Is the metadata necessary?

**Comment by iCrawl** [comment]
There's just one thing I'd like to confirm.

image
image

Can we compare VSCode versions perhaps?

image

**Comment by PlayTheFallen** [comment]
My bad, might just be a VSCode stable build issue as the components haven't been released yet.  
Discord RP isn't working as of this change *locally* on the stable build.

*After downloading the latest version of VSCode Insiders*  
Insiders has the same preference on the configuration property as Stable does.  
  
*can't get 1.19-Insider for some reason...*

**Comment by iCrawl** [comment]
It looks to me like you were running an outdated version of VSCode. 1.15 is very old.
Latest stable is 1.18.x and latest Insiders is 1.19.x

**Comment by PlayTheFallen** [comment]
I will look into updating my version of vsc *i don't have admin on the computer i run it on, so i have to request it instead*.

Thank you anyway for reviewing this.

**Pull request closed without merging**
