### PR TITLE
Added more languages

### PR DESCRIPTION
**Pull request by smokes**
I have redesigned  the RPC's Icons and edited Activity.ts to support fileNames and not just extensions, i'll send a link to a google drive folder If you'd like me to.

here's some examples 
image
image

image

image
image

### CODE REVIEW

**Comment by iCrawl** [comment]
This looks pretty nice, only complaint would be that you changed the indentation of the JSON file from tabs to spaces as I see it?

**Comment by smokes** [comment]
oooh yeah i'll fix it

**Comment by smokes** [comment]
Converted spaces to tabs. Here's a repo containing the assets https://github.com/smokes/vscode-discord-assets

**Comment by iCrawl** [comment]
Dope man, great work. I'll get on merging that and updating the icons over the course of the day and release a new version!

**Pull request merged**
